### ISSUE TITLE
Does "deepsleep" command work for you?

### ISSUE THREAD

**Issue by pfalcon** [nekromant/esp8266-frankenstein#1]
For me, it prints some garbage and locks up module. I'm using gcc, libhal and newlib built from source.

**Comment by PasiOjala** [comment]
@alonewolfx2: could you please point me to how to put esp-1 to deep sleep... i.e. how to connect the GPIO16 and RST on the module?  Did you just solder a jumper directly on the SOC pins, or is there a place for a jumper on the board?

**Comment by alonewolfx2** [comment]
Esp03 have on board place for soldering. Esp01 don't have. I use both. I am using 0 ohm resistor on esp03 and I soldered directly on esp01 soc.
