### ISSUE TITLE
Handling of whitespace in arguments

### ISSUE THREAD

**Issue by Chaemelion** [nekromant/esp8266-frankenstein#15]
From what I can tell, the command interpreter splits args on whitespace, correct? Without escaping methods, I'm unable to connect to SSIDs that contain whitespace.

**Comment by nekromant** [comment]
Yep, that's a limitation of microrl. See src/microrl.c 
From what I've seen adding whitespace handling might be a little tricky, but doable. It's somewhere on my TODO list.

**Comment by Chaemelion** [comment]
Gotcha. The original AT firmware appears to delimit on commas, perhaps that would provide a simple temporary fix rather than full implementation of escape sequences. When I finally get my libs, includes, and paths configured correctly, I'll play around with testing some fixes.

**Comment by d-a-v** [comment]
would the latest pull request solve this issue?

**Comment by nekromant** [comment]
Yeah, it does. Thanks for fixing this one, I'm closing the issue.
