### ISSUE TITLE
Can't set password for access point

### ISSUE THREAD

**Issue by riban-bw** [nekromant/esp8266-frankenstein#16]
Using the command **apconfig** to setup an access point with encryption does not allow the 3rd parameter (password) to be set. An error message is issued:

> Command apconfig takes a maximum of 3 args, 4 given

**Comment by lucaspiller** [comment]
I'm also getting this error, my access point has spaces in it which I think is the issue.

I've tried both `"access point"` and `access\ point`, but to no avail.

**Comment by nekromant** [comment]
@lucaspiller This is fixed in master, either recompile yourself or wait till I push an updated binary to git.
