### ISSUE TITLE
Telnet needs authorisation

### ISSUE THREAD

**Issue by nekromant** [nekromant/esp8266-frankenstein#54]
Otherwise we'll forget about it.

**Comment by d-a-v** [comment]
On mar., mars 24, 2015 at 08:09:01 -0700, Andrew wrote:
> Otherwise we'll forget about it. 

Do you mean a password ?

I've been thinking of a no-auth telnet but auth required for
sensible commands through telnet so anyone could read sensors
but not reset nor tftp update nor show env (showing passwords), ...
unless authorized through a sort of sudo command.

**Comment by nekromant** [comment]
That mode would require a lot of hackery as I see it. e.g. add permission section for every command. Just add a plain login/password prompt that can be turned off. Automated scripts will have no problem to supply that.

**Comment by darkbyte-ru** [comment]
For single user mode only password check will be enough. If password was not set in env, so allow auth to everyone.

**Comment by nekromant** [comment]
@darkbyte-ru Sound's like it should be enough.

**Comment by nekromant** [comment]
Implemented in current master, closing this issue.
