### ISSUE TITLE
make mrproper results in "Error 1"

### ISSUE THREAD

**Issue by susisstrolch** [nekromant/esp8266-frankenstein#64]
it seems that "make mrproper" (on current master 82ae8af) doesn't clean inside ./antares:
>strolch@strolch /home/strolch/Development/Espressif/share/Repos/frankenstein $ make mrproper
  [GEN]       /home/strolch/Development/Espressif/share/Repos/frankenstein/tmp/edeploy.mk
  [GEN]       /home/strolch/Development/Espressif/share/Repos/frankenstein/tmp/deploy.mk
  [GEN]       /home/strolch/Development/Espressif/share/Repos/frankenstein/tmp/arch.mk
  [CLEAN]     cleaning up build directory and temporary files
  [MRPROPER]  purging everything
rm: cannot remove ‘/home/strolch/Development/Espressif/share/Repos/frankenstein/antares’: Is a directory
make: *** [mrproper] Error 1

After that, "make" and "make build" aren't possible anymore:
> @strolch /home/strolch/Development/Espressif/share/Repos/frankenstein $ make
Missing configuration file (.config). Please run configuation tool (menuconfig, etc))

>@strolch /home/strolch/Development/Espressif/share/Repos/frankenstein $ make build
make: *** No rule to make target ./.bin', needed by `build'.  Stop.

Running "make defconfig; make" compiles all files, but lastly leads to
>...
/home/strolch/Development/Espressif/share/Repos/frankenstein/antares/include/lib/heatshrink_config.h:6:35: warning: "CONFIG_LIB_HEATSHRINK_DYNAMIC_ALLOC" is not defined [-Wundef]
 #define HEATSHRINK_DYNAMIC_ALLOC  CONFIG_LIB_HEATSHRINK_DYNAMIC_ALLOC
                                   ^
/home/strolch/Development/Espressif/share/Repos/frankenstein/antares/src/lib/compression/heatshrink_decoder.c:50:5: note: in expansion of macro 'HEATSHRINK_DYNAMIC_ALLOC'
 #if HEATSHRINK_DYNAMIC_ALLOC
     ^
  [GEN]       built-in.o
  [GEN]       built-in.o
  [GEN]       built-in.o
  [IROMIFY]   Moving application code to IROM
  [LD]        images/antares.elf
/home/strolch/Development/Espressif/share/Repos/esp-open-sdk/xtensa-lx106-elf/lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld: cannot open output file images/antares.elf: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [images/antares.elf] Error 1

**Comment by nekromant** [comment]
Is antares in your project root a directory or a symlink to a system-wide installation?

**Comment by susisstrolch** [comment]
It's a regular directory - created by the initial "make" of frankenstein.

Ah - the mrproper also deletes the images/ directory, but it doesn't get 
rebuild by make or make build...

**Comment by nekromant** [comment]
Actually, it does. But due to failing to delete antares dir mrproper doesn't remove all the other stuff so next time you run build the initial directory creation magic is not run. 
Since I use antares for a ton of project the usual mode is 'symlink' antares to each project.  
I have committed fixes in both antares tree and frankenstein that should fix this issue for now. Try a clean build.
