### ISSUE TITLE
building

### ISSUE THREAD

**Issue by digger3d** [nekromant/esp8266-frankenstein#77]
anton@Satellite-A105:~/esp8266-frankenstein$ make build
  [INFO]      Building antares library code and startup
  [GEN]       built-in.rel
  [GEN]       built-in.rel
  [GEN]       built-in.rel
  [GEN]       built-in.rel
  [GEN]       built-in.rel
  [GEN]       built-in.rel
  [GEN]       built-in.rel
  [GEN]       built-in.rel
  [INFO]      Building application code
  [CC]        main.rel
/home/anton/esp8266-frankenstein/src/main.c:4:21: fatal error: ets_sys.h: No such file or directory
compilation terminated.
/home/anton/esp8266-frankenstein/antares/make/Makefile.build:78: recipe for target 'main.rel' failed
make[1]: *** [main.rel] Error 1
/home/anton/esp8266-frankenstein/antares/toolchains/sdcc.mk:38: recipe for target 'builtin' failed
make: *** [builtin] Error 2

**Comment by nekromant** [comment]
Why are you trying to compile it with sdcc? 
start with make defconfig
and later adjust when needed,

**Comment by nekromant** [comment]
See #74
