### ISSUE TITLE
Build against SDK 1.0.1b2 is broken

### ISSUE THREAD

**Issue by nekromant** [nekromant/esp8266-frankenstein#82]
Looks like we have a problem with 1.0.1b2 SDK, something's changed and it can't ever connect to a network. Now trying to figure out where the insect came from.

**Comment by d-a-v** [comment]
I did not try, but I came into this: https://github.com/themadinventor/esptool/issues/33
Could it be related ?

**Comment by nekromant** [comment]
Unlikely. My guess is that something's changed in headers yet again, but I may be wrong. 
The firmware is working, I can access commandline and even scan for networks, but whenever I try to connect the console becomes laggy and occasionally ends up in an exception and a reboot. I could never connect to a network on 1.0.1b2, while 1.0.1b1 worked awesomely.

**Comment by susisstrolch** [comment]
On 04/30/2015 12:43 PM, Andrew wrote:
>
> Unlikely. My guess is that something's changed in headers yet again, 
> but I may be wrong.
> The firmware is working, I can access commandline and even scan for 
> networks, but whenever I try to connect the console becomes laggy and 
> occasionally ends up in an exception and a reboot. I could never 
> connect to a network on 1.0.1b2, while 1.0.1b1 worked awesomely.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nekromant/esp8266-frankenstein/issues/82#issuecomment-97735365>.
>
Another flaw - not really the reason for that problem - is the default 
base address for environment.
According to SDK doc, the last 16k are used by the system.
So, the default should be set to 0x7B000 instead 0x7C000.

**Comment by nekromant** [comment]
Now fixed, and builds against 2.0
