### ISSUE TITLE
Hello from ScratchABit

### ISSUE THREAD

**Issue by pfalcon** [nekromant/esp8266-frankenstein#86]
@nekromant : I've mentioned it to you (via @nekromant) elsewhere, not sure if you saw it though, so continuing spam campaign: please mind existence of https://github.com/pfalcon/ScratchABit . It works with https://github.com/themadinventor/ida-xtensa (actually, working with it was one (but only one) reason to develop it). And I have more goodies in https://github.com/pfalcon/ida-xtensa (contributing upstream bit by bit, but as I don't use IDA, more advanced changes may be hard to spool).

**Comment by nekromant** [comment]
Thanks, will keep that in mind. For I still use objdump -S for most of my disassembly needs.
