### ISSUE TITLE
Problem bad crc environment

### ISSUE THREAD

**Issue by Rojer-x86** [nekromant/esp8266-frankenstein#88]
I noticed that if enable sta-auto then after second reboot give error crc environment.
After reading source code I found error in src/iwconnect.c 51 line wifi_station_set_config(&sta_conf).
In SDK >= 1.0.0 function wifi_station_set_config makes settings connection and save this parameters in flash memory for settings connection without save parameters used function wifi_station_set_config_current.
Also found error in style "copy-paste" file src/cmd_env.c 89 line HELPSTR_NEWLINE "setenv var value" I think must be "saveenv".

Заметил что при включение sta-auto после 2 ребута слетает переменное окружение с ошибкой crc.
ковыряние в исходниках дало результат src/iwconnect.c 51 строка wifi_station_set_config(&sta_conf).
в SDK >= 1.0.0 wifi_station_set_config настраивает подключение а также сохраняет в flash по этому надо использовать wifi_station_set_config_current. также заметил в коде ошибку копи-паста src/cmd_env.c 89 строка HELPSTR_NEWLINE "setenv var value" но там скорее имели виду "saveenv".

**Comment by nekromant** [comment]
1. The flash offset that blobs store their config to have changed several times. That is really annoying. You can adjust the offset of the environment using menuconfig so that they will not overlap. 
2. As for the rest, I'll give it a look as soon as I get closer to the actual hardware.
