### ISSUE TITLE
Problem building firmware

### ISSUE THREAD

**Issue by digger3d** [nekromant/esp8266-frankenstein#91]
Followed all the instructions at  https://github.com/nekromant/esp8266-frankenstein/blob/master/README.hacking

this is my Ubuntu system at Virtualbox:
esp@esp-master:~/firmware/esp8266-frankenstein$ uname -a
Linux esp-master 4.2.0-19-generic #23-Ubuntu SMP Wed Nov 11 11:38:40 UTC 2015 i686 i686 i686 GNU/Linux

here is the build error message:

 [IROMIFY]   Moving application code to IROM
  [LD]        images/antares.elf
/home/esp/firmware/esp-open-sdk/xtensa-lx106-elf/lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld: images/antares.elf section `.irom0.text' will not fit in region`irom0_0_seg'
/home/esp/firmware/esp8266-frankenstein/build/app/cmd_flash.o: In function `do_scan':
cmd_flash.c:(.irom0.text+0xf8): undefined reference to`wdt_feed'
/home/esp/firmware/esp8266-frankenstein/build/app/cmd_flash.o: In function `do_dump':
cmd_flash.c:(.irom0.text+0x1ab): undefined reference to`wdt_feed'
/home/esp/firmware/esp8266-frankenstein/build/app/cmd_i2c.o: In function `do_i2c':
cmd_i2c.c:(.irom0.text+0x238): undefined reference to`wdt_feed'
/home/esp/firmware/esp8266-frankenstein/build/app/mqtt/mqtt.o: In function `MQTT_Subscribe':
mqtt.c:(.irom0.text+0x7a0): undefined reference to`mqttGetConnectedClient'
mqtt.c:(.irom0.text+0x7bf): undefined reference to `mqttGetConnectedClient'
/home/esp/firmware/esp-open-sdk/xtensa-lx106-elf/xtensa-lx106-elf/sysroot/usr/lib/libssl.a(espconn_ssl.o): In function`espconn_ssl_read':
(.irom0.text+0xcc): undefined reference to `espconn_kill_oldest_pcb'
/home/esp/firmware/esp-open-sdk/xtensa-lx106-elf/xtensa-lx106-elf/sysroot/usr/lib/libssl.a(espconn_ssl.o): In function`espconn_ssl_read':
(.irom0.text+0xdd): undefined reference to `espconn_kill_oldest_pcb'
/home/esp/firmware/esp-open-sdk/xtensa-lx106-elf/xtensa-lx106-elf/sysroot/usr/lib/libssl.a(espconn_ssl.o): In function`espconn_ssl_read':
(.irom0.text+0x147): undefined reference to `espconn_kill_oldest_pcb'
collect2: error: ld returned 1 exit status
/home/esp/firmware/esp8266-frankenstein/antares/toolchains/gcc.mk:158: recipe for target 'images/antares.elf' failed
make: **\* [images/antares.elf] Error 1
What do I do?

**Comment by nekromant** [comment]
Try out the new cmake refactor, that should do the trick. Just make sure you have SDK 2.0 or higher in standalone mode.
