### ISSUE TITLE
ping linking resolve

### ISSUE THREAD

**Issue by akaJes** [nekromant/esp8266-frankenstein#92]
in
esp8266-frankenstein/src/cmd_ping.c
# include "console.h"
# include "ping.h"
# include <stdlib.h>
# include <generic/macros.h>

//TODO: cmd_ping.c:(.irom0.text+0x2d): undefined reference to `ping_start'

U need wrap into 
extern "C" {
# include "ping.h"

}

**Comment by nekromant** [comment]
Fixed in most recent cmake branch
